# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ds9gLvPUSqV13ELC8REyXLxUFcOfqMcz
"""
import requirements.txt
import pandas as pd
import folium
from folium.plugins import MarkerCluster
from streamlit_folium import st_folium
import streamlit as st


st.title('Bazar Ramadan Locations in Kuala Lumpur 2025')

# Upload CSV file
uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file:
    data = pd.read_csv(uploaded_file)

    # Initialize the map
    m = folium.Map(location=[3.1390, 101.6869], zoom_start=12)
    marker_cluster = MarkerCluster().add_to(m)

    # Add markers
    for idx, row in data.iterrows():
        lat, lon = map(float, row['GPS Coordinates'].split(','))
        popup_info = f"""
        <b>Location:</b> {row['Location']}<br>
        <b>Number of Stalls:</b> {row['Number of Stalls']}<br>
        <b>Remarks:</b> {row['Remarks']}
        """
        folium.Marker(
            location=[lat, lon],
            popup=folium.Popup(popup_info, max_width=300),
            icon=folium.Icon(color='red', icon='info-sign')
        ).add_to(marker_cluster)

    # Display the map
    st_folium(m, width=700, height=500)
else:
    st.warning("Please upload a CSV file to view the map.")
